In [1]:
import os
import pandas as pd
import numpy as np
import pybaseball as pb

In [2]:

START = 2002
END = 2022

In [3]:
if os.path.exists("batting.csv"):
    batting = pd.read_csv("batting.csv", index_col=0)
else:
    batting = batting_stats(START, END, qual=200)
    batting.to_csv("batting.csv")

In [4]:
batting = batting.groupby("IDfg", group_keys=False).filter(lambda x: x.shape[0] > 1)

In [5]:
batting.head(10)

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA
Column1,,,,,,,,,,,,,,,,,,,,,
0.0,1109.0,2002.0,Barry Bonds,SFG,37.0,143.0,403.0,612.0,149.0,70.0,...,NaN,NaN,NaN,NaN,0.0,0.127,0.191,NaN,NaN,NaN
1.0,1109.0,2004.0,Barry Bonds,SFG,39.0,147.0,373.0,617.0,135.0,60.0,...,NaN,NaN,NaN,NaN,0.0,0.124,0.164,NaN,NaN,NaN
15.0,13611.0,2018.0,Mookie Betts,BOS,25.0,136.0,520.0,614.0,180.0,96.0,...,0.131,110.6,217.0,0.500,434.0,0.220,0.270,NaN,NaN,NaN
2.0,1109.0,2003.0,Barry Bonds,SFG,38.0,130.0,390.0,550.0,133.0,65.0,...,NaN,NaN,NaN,NaN,0.0,0.135,0.223,NaN,NaN,NaN
78.0,10155.0,2013.0,Mike Trout,LAA,21.0,157.0,589.0,716.0,190.0,115.0,...,NaN,NaN,0.0,NaN,0.0,0.200,0.266,NaN,NaN,NaN
170.0,10155.0,2012.0,Mike Trout,LAA,20.0,139.0,559.0,639.0,182.0,117.0,...,NaN,NaN,0.0,NaN,0.0,0.221,0.293,NaN,NaN,NaN
190.0,9166.0,2012.0,Buster Posey,SFG,25.0,148.0,530.0,610.0,178.0,114.0,...,NaN,NaN,0.0,NaN,0.0,0.190,0.251,NaN,NaN,NaN
74.0,1274.0,2002.0,Alex Rodriguez,TEX,26.0,162.0,624.0,725.0,187.0,101.0,...,NaN,NaN,NaN,NaN,0.0,0.169,0.279,NaN,NaN,NaN
11.0,15640.0,2022.0,Aaron Judge,NYY,30.0,139.0,513.0,616.0,159.0,79.0,...,0.254,118.4,220.0,0.601,366.0,0.176,0.292,NaN,NaN,NaN
77.0,639.0,2004.0,Adrian Beltre,LAD,25.0,156.0,598.0,657.0,200.0,120.0,...,NaN,NaN,NaN,NaN,0.0,0.130,0.232,NaN,NaN,NaN

In [6]:
def next_season(player):
    player = player.sort_values("Season")
    player["Next_WAR"] = player["WAR"].shift(-1)
    return player

batting = batting.groupby("IDfg", group_keys=False).apply(next_season)

In [7]:
null_count = batting.isnull().sum()

In [8]:
complete_cols = list(batting.columns[null_count == 0])
batting = batting[complete_cols + ["Next_WAR"]].copy()

In [9]:
batting

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,Pull%+,Cent%+,Oppo%+,Soft%+,Med%+,Hard%+,Events,CStr%,CSW%,Next_WAR
Column1,,,,,,,,,,,,,,,,,,,,,
5549.0,1.0,2006.0,Alfredo Amezaga,FLA,28.0,132.0,334.0,378.0,87.0,72.0,...,86.0,107.0,113.0,143.0,109.0,63.0,0.0,0.188,0.256,2.0
5000.0,1.0,2007.0,Alfredo Amezaga,FLA,29.0,133.0,400.0,448.0,105.0,80.0,...,92.0,101.0,112.0,109.0,113.0,75.0,0.0,0.175,0.227,1.2
5243.0,1.0,2008.0,Alfredo Amezaga,FLA,30.0,125.0,311.0,337.0,82.0,61.0,...,99.0,101.0,101.0,123.0,111.0,64.0,0.0,0.178,0.244,NaN
1168.0,2.0,2002.0,Garret Anderson,ANA,30.0,158.0,638.0,678.0,195.0,107.0,...,118.0,91.0,80.0,65.0,97.0,129.0,0.0,0.137,0.232,5.1
866.0,2.0,2003.0,Garret Anderson,ANA,31.0,159.0,638.0,673.0,201.0,119.0,...,112.0,101.0,80.0,90.0,99.0,109.0,0.0,0.164,0.252,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5980.0,24655.0,2022.0,Owen Miller,CLE,25.0,119.0,391.0,433.0,97.0,66.0,...,92.0,111.0,99.0,127.0,102.0,82.0,315.0,0.191,0.269,NaN
4880.0,26197.0,2021.0,Andrew Vaughn,CHW,23.0,127.0,417.0,469.0,98.0,61.0,...,87.0,104.0,116.0,84.0,99.0,110.0,321.0,0.185,0.285,0.5
2097.0,26197.0,2022.0,Andrew Vaughn,CHW,24.0,118.0,456.0,497.0,132.0,88.0,...,88.0,108.0,108.0,93.0,99.0,105.0,382.0,0.205,0.287,NaN
6604.0,27506.0,2021.0,Ha-seong Kim,SDP,25.0,117.0,267.0,298.0,54.0,32.0,...,126.0,99.0,59.0,137.0,96.0,88.0,201.0,0.216,0.303,2.6
4920.0,27506.0,2022.0,Ha-seong Kim,SDP,26.0,132.0,451.0,507.0,111.0,75.0,...,117.0,101.0,71.0,119.0,102.0,87.0,367.0,0.199,0.274,NaN

In [10]:
batting.dtypes[batting.dtypes == "object"]

Name       object
Team       object
Age Rng    object
dtype: object

In [11]:
del batting["Age Rng"]
del batting["Dol"]

In [12]:
batting["team_code"] = batting["Team"].astype("category").cat.codes

C:\Users\brand\AppData\Local\Temp\ipykernel_19624\2275808249.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  batting["team_code"] = batting["Team"].astype("category").cat.codes

In [13]:
batting_full = batting.copy()
batting = batting.dropna().copy()

In [14]:
from sklearn.linear_model import Ridge
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

rr = Ridge(alpha=1)

split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, 
                                n_features_to_select=20, 
                                direction="forward",
                                cv=split,
                                n_jobs=8
                               )

In [15]:
removed_columns = ["Next_WAR", "Name", "Team", "IDfg", "Season"]
selected_columns = batting.columns[~batting.columns.isin(removed_columns)]

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
batting.loc[:,selected_columns] = scaler.fit_transform(batting[selected_columns])

In [17]:
sfs.fit(batting[selected_columns], batting["Next_WAR"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=Ridge(alpha=1), n_features_to_select=20,
                          n_jobs=8)

In [18]:
predictors = list(selected_columns[sfs.get_support()])

In [19]:
predictors

['Age',
 'IBB',
 'SO',
 'SB',
 'BU',
 'BABIP',
 'IFH%',
 'WAR',
 'Spd',
 'PH',
 'CB%',
 'Z-Contact%',
 'SwStr%',
 'wGDP',
 'Oppo%',
 'SLG+',
 'LD+%',
 'Pull%+',
 'Soft%+',
 'Hard%+']

In [20]:
def backtest(data, model, predictors, start=5, step=1):
    all_predictions = []
    
    years = sorted(data["Season"].unique())
    
    for i in range(start, len(years), step):
        current_year = years[i]
        train = data[data["Season"] < current_year]
        test = data[data["Season"] == current_year]
        
        model.fit(train[predictors], train["Next_WAR"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["Next_WAR"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [21]:
predictions = backtest(batting, rr, predictors)

In [35]:
predictions

         actual  prediction
Column1
5000.0      1.2    1.434230
1923.0      1.4    0.586508
3108.0     -0.1    0.557548
5782.0      0.6    0.976339
1108.0      4.8    2.202436
...         ...         ...
1913.0      1.2    2.680792
5863.0      1.0    1.763499
7009.0      0.6    1.250112
4880.0      0.5    1.446408
6604.0      2.6    1.128072

[4115 rows x 2 columns]

In [22]:
predictions.shape

(4115, 2)

In [23]:
from sklearn.metrics import mean_squared_error

mean_squared_error(predictions["actual"], predictions["prediction"])

2.7671807143292715

In [24]:
def player_history(df):
    df = df.sort_values("Season")
        
    df["player_season"] = range(0, df.shape[0])
    df["war_corr"] = list(df[["player_season", "WAR"]].expanding().corr().loc[(slice(None), "player_season"),"WAR"])
    df["war_corr"].fillna(0, inplace=True)
    
    df["war_diff"] = df["WAR"] / df["WAR"].shift(1)
    df["war_diff"].fillna(1, inplace=True)
    df["war_diff"][df["war_diff"] == np.inf] = 1
    
    return df

batting = batting.groupby("IDfg", group_keys=False).apply(player_history)

In [25]:
def group_averages(df):
    return df["WAR"] / df["WAR"].mean()

In [26]:
batting["war_season"] = batting.groupby("Season", group_keys=False).apply(group_averages)

In [27]:
new_predictors = predictors + ["player_season", "war_corr", "war_season", "war_diff"]

In [28]:

predictions = backtest(batting, rr, new_predictors)

In [29]:
mean_squared_error(predictions["actual"], predictions["prediction"])

2.674753807939871

In [30]:
pd.Series(rr.coef_, index=new_predictors).sort_values()

Age             -2.685008
WAR             -1.926992
BABIP           -1.564527
SLG+            -1.254824
Soft%+          -1.253514
SwStr%          -1.034504
BU              -1.001154
PH              -0.729490
SO              -0.664919
Z-Contact%      -0.658578
war_diff        -0.589077
wGDP            -0.469103
CB%             -0.258188
Pull%+          -0.232500
LD+%            -0.231191
war_corr        -0.086429
player_season    0.008270
IFH%             0.383520
Oppo%            0.657206
Spd              0.708913
SB               1.048349
IBB              1.812376
Hard%+           2.262003
war_season       3.471276
dtype: float64

In [31]:
diff = predictions["actual"] - predictions["prediction"]

In [32]:
merged = predictions.merge(batting, left_index=True, right_index=True)

In [33]:
merged["diff"] = (predictions["actual"] - predictions["prediction"]).abs()

In [34]:
merged[["IDfg", "Season", "Name", "WAR", "Next_WAR", "diff"]].sort_values(["diff"])

            IDfg  Season               Name       WAR  Next_WAR      diff
Column1
1585.0    2158.0  2008.0         Greg Dobbs  0.267081      -0.1  0.000816
6448.0    1818.0  2007.0       Bobby Crosby  0.211180       1.3  0.000926
963.0    13066.0  2021.0  Teoscar Hernandez  0.478261       2.1  0.001077
1364.0    1849.0  2014.0   Rickie Weeks Jr.  0.291925      -0.1  0.001349
3432.0   14854.0  2021.0   Mike Yastrzemski  0.360248       1.4  0.001460
...          ...     ...                ...       ...       ...       ...
3165.0    4810.0  2007.0       Brian McCann  0.304348       8.6  6.378203
3249.0    5631.0  2010.0          Matt Kemp  0.211180       8.3  6.380206
3825.0    1875.0  2009.0      Josh Hamilton  0.291925       8.4  6.580501
873.0     9166.0  2010.0       Buster Posey  0.459627      10.1  6.610423
2519.0   11579.0  2014.0       Bryce Harper  0.310559       9.3  7.554978

[4115 rows x 6 columns]